# Site settings
title: samratcliffe
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I am a web developer based out of Washington, D.C.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://samratcliffe.github.io" # the base hostname & protocol for your site
github_username:  samratcliffe
permalink: /:title

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge