# Site settings
title: samratcliffe
email: your-email@domain.com
description: "I'm a dev from the southern hemisphere but living in the northern. I make interactive web components and a mean spaghetti bolognese. This site is a motley crew of things I'm working on or thinking about."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://samratcliffe.github.io" # the base hostname & protocol for your site
github_username:  samratcliffe
permalink: /:title

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge